{% set name = "sacc" %}
{% set version = "0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/sacc/archive/v{{ version }}.tar.gz
  sha256: d662649cfc2ccc6dd1e7d21c2e9f168280bbc266c16f7288fc420d095631483d

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm <7
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - astropy
    - scipy
    - numpy

test:
  imports:
    - sacc

about:
  home: https://github.com/LSSTDESC/sacc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Save All Correlations and Covariances

extra:
  recipe-maintainers:
    - joezuntz
    - beckermr
