{% set name = "sacc" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/sacc/archive/v{{ version }}.tar.gz
  sha256: 3f5373ee04d3f59c8464a208a0a5a217f1e5e98f5a286a5825b152515ebd507b

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm <7
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - astropy
    - scipy
    - numpy
    - numpydoc

test:
  imports:
    - sacc

about:
  home: https://github.com/LSSTDESC/sacc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Save All Correlations and Covariances

extra:
  recipe-maintainers:
    - joezuntz
    - beckermr
